### ISSUE TITLE
Fetch token price on Hedera network

### ISSUE THREAD

**Issue by CryptoFist** [LimeChain/HeliSwap-contracts#39]
I need to token price on Hedera network.
On other EVM networks, I used chainlink oracle to fetch token price.
But on Hedera, I couldn't find out such contract for fetching price. 
Can you let me know how I can get fetch a token price on Hedera network?

**Comment by RAMTO** [comment]
HELI token price or a particular token price?

**Comment by CryptoFist** [comment]
Any token price.

**Comment by RAMTO** [comment]
I do not think there is a general/common way to do that.
